### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by betterliu-code** [gulihua10010/chatGptApiSdk#18]
is:issue is:open java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure 	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45) 	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90) 	at io.reactivex.Single.blockingGet(Single.java:2002)是什么问题导致的呀

**Comment by gulihua10010** [comment]
网络问题，要么就是你的 jdk 版本问题
