### ISSUE TITLE
GPT4模型如何发布图文对话

### ISSUE THREAD

**Issue by skyliwq** [gulihua10010/chatGptApiSdk#19]
看官方问题格式是 content:['内容',{image:...}] 这里怎么添加！

**Comment by gulihua10010** [comment]
GPT-4 的 api 我看官方文档没有写，我的申请两个月一直在等待列表里，所以不清楚它的具体格式，你这个格式是哪里看到的？或者说如果你有具体 GPT-4 的API文档说明，可以给我分享下么

**Comment by skyliwq** [comment]
那等到GPT-4 正式出的时候在调整吧 我是在一段视频中看到的 我也没有官方文档
