### ISSUE TITLE
流式的有点问题呀

### ISSUE THREAD

**Issue by fl1906** [gulihua10010/chatGptApiSdk#2]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/73702449/222647690-51d00c6c-5491-4739-92fc-0e778ad90fa9.png">

**Comment by gulihua10010** [comment]
流式的返回的数据是有点问题，我在改
如果超时的话，试试代理

**Comment by gulihua10010** [comment]
更新下项目或者升级下pom 依赖1.0.3 后再试试，
@Test测试异步方法需要加个同步工具，比如CountDownLatch
