### ISSUE TITLE
创建出来的微调模型如何使用？？

### ISSUE THREAD

**Issue by skyliwq** [gulihua10010/chatGptApiSdk#21]
创建出来的微调模型如何使用？？没找到dome,我在官网测试出现违禁词汇为什么？

**Comment by gulihua10010** [comment]
在completions时指定你创建的微调模型的模型名称就行了 
啥违禁词汇，这种我没遇到过

**Comment by skyliwq** [comment]
删除Fine-tunes 无效 无法删除The model 'curie:ft-sailer-fei-2023-05-15-01-08-02' does not exist

**Comment by gulihua10010** [comment]
你用 api 接口直接删呢
