### ISSUE TITLE
embeddings接口能否支持数组，我看官方文档是支持数组的

### ISSUE THREAD

**Issue by hangyi24579** [gulihua10010/chatGptApiSdk#23]
embeddings能否支持数组，我看官方文档是支持数组的

**Comment by gulihua10010** [comment]
你说的是请求的 input 参数吗

**Comment by hangyi24579** [comment]
> 你说的是请求的输入 参数吗

对

**Comment by hangyi24579** [comment]
输入文本以获取嵌入，编码为字符串或标记数组。要在单个请求中获取多个输入的嵌入，请传递一个字符串数组或令牌数组数组。每个输入的长度不得超过 8192 个标记。

文档上是这样写的

**Comment by gulihua10010** [comment]
已经提交修复 (v1.0.12 ) 
同步到中央仓库可能会有延迟
