### ISSUE TITLE
调用openapi速度很慢，请问怎么解决的？

### ISSUE THREAD

**Issue by xiangyichang** [gulihua10010/chatGptApiSdk#8]
service.completionsChat(req)
基本都是是在40秒左右. 尤其在记住上下文中

流式又不能给出一个总的结果

**Comment by gulihua10010** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/38686919/225542922-990269bf-4cb1-4104-a598-051197db10d5.png">
是不是你连接的代理的问题，我的平均 8-15 秒，没超过 20 秒的

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/38686919/225543152-9b3344bf-4d2f-45cf-927e-8b816d7b6cac.png">
流式的接口响应就是一个字一个字返回的

**Comment by xiangyichang** [comment]
没用代理，把接口放到了外面服务器上。
21574毫秒, CompletionRes(id=chatcmpl-6wunEzk9AI2cYCrj6uWPQCOHIRkmq, object=chat.completion, created=1679499356, model=gpt-3.5-turbo-0301, choices=[Choices(text=, index=0, logprobs=null, message=MessageReq(role=assistant, content=
基本在20秒左右
